version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blife-backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '3013:3013'
    depends_on:
      - db 

  db:
    image: postgres:latest 
    container_name: blife-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local