version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blife-backend
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - '3013:3013'